const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const html=fs.readFileSync(__dirname+'/index.html','utf8'),code=html.match(/<script>([\s\S]*?)<\/script>/)[1];
function harness(extra={}){
  const storage=new Map(),nodes={};let time=0,intervalFn=null,clearCount=0,rendered='';
  class Clock extends Date{constructor(...args){super(...(args.length?args:[time]));}static now(){return time;}}
  const context=vm.createContext({Date:Clock,URL,Blob,console,crypto:require('node:crypto').webcrypto,load:(k,d)=>storage.has(k)?JSON.parse(storage.get(k)):d,localStorage:{setItem:(k,v)=>storage.set(k,v)},window:{addEventListener(){}},scripts:[],scores:[],LS:{scripts:'scripts',scores:'scores'},save:(k,v)=>storage.set(k,JSON.stringify(v)),esc:x=>String(x||''),styleScriptText:x=>x,recordingNavigationAllowed:()=>true,toast:()=>{},openOverlay:(k,h)=>{vm.runInContext('if(overlayCleanup){overlayCleanup();overlayCleanup=null;}',context);rendered=h;},$:id=>nodes[id]??={value:'',textContent:'',hidden:false,disabled:false,pause(){this.paused=true;}},renderRateDots:(id,s,choose,clear)=>{nodes.rate={choose,clear};},setMastery:(s,n)=>s.mastery=n,markPracticed:s=>s.lastPracticed='2026-09-16',setInterval:fn=>{intervalFn=fn;return 1;},clearInterval:()=>{clearCount++;intervalFn=null;},...extra});
  vm.runInContext(code.slice(code.indexOf('function parseSteps'),code.indexOf('function openLiveCall')),context);
  vm.runInContext(code.slice(code.indexOf('function localDay'),code.indexOf('function currentStreak')),context);
  vm.runInContext(code.slice(code.indexOf('function rankPractice'),code.indexOf('const editableScriptFields')),context);
  vm.runInContext(code.slice(code.indexOf('/* ---------- workflow add-ons'),code.indexOf('/* ---------- VAULT backup')),context);
  return {context,nodes,storage,run:js=>vm.runInContext(js,context),advance(ms){time+=ms;intervalFn?.();},get rendered(){return rendered;},get clearCount(){return clearCount;}};
}
const flow=()=>({id:'expired',title:'Expired',category:'Call Flow',leadType:'Expired',mastery:2,text:'1 - OPENING\nHi John, about [street].\n2 - DISCOVERY\nTell me about [their outcome].'});
test('delivery cues appear before their selected line and tolerate edited-away anchors',()=>{const h=harness();h.context.s={stepCues:{Opening:'Pause'},cueAnchors:{Opening:'Second line'}};const result=h.run('callBodyWithCues(s,"Opening","First line\\nSecond line",{})');assert.ok(result.indexOf('Delivery cue: Pause')>result.indexOf('First line'));assert.ok(result.indexOf('Delivery cue: Pause')<result.indexOf('Second line'));assert.equal(h.run('callBodyWithCues(s,"Opening","Changed line",{})'),'Changed line');});
test('phrase search combines default and custom aliases without requiring exact wording',()=>{const h=harness();h.context.s={title:'Not selling',text:'A response',objection:'Not selling',aliases:'happy here'};assert.equal(h.run('matchesScript(s,"We’re staying put")'),true);assert.equal(h.run('matchesScript(s,"staying put")'),true);assert.equal(h.run('matchesScript(s,"happy here")'),true);assert.equal(h.run('matchesScript(s,"commission")'),false);});
test('call personalization handles literal dollar characters and never mutates source',()=>{const h=harness();h.context.s=flow();h.context.fields={name:'A$&',street:'Main $1',outcome:'downsizing'};assert.equal(h.run('substituteCall(s.text,fields)').includes('Hi A$&, about Main $1.'),true);assert.match(h.context.s.text,/John/);assert.equal(h.storage.size,0);});
test('practice packs include the selected flow, shared handlers and closer, excluding another lead type',()=>{const h=harness();h.context.scripts=[flow(),{id:'fsbo',category:'Call Flow',leadType:'FSBO'},{id:'common',category:'Objection Handler'},{id:'fsbo-only',category:'Objection Handler',leadType:'FSBO'},{id:'close',category:'Appointment Close'}];assert.equal(h.run('packScripts(scripts[0]).map(s=>s.id).join(",")'),'expired,common,close');});
test('targeted sections outrank unflagged scripts and stale labels fall back safely',()=>{const h=harness();const s=flow();s.mastery=5;s.practiceTargets=['2 - DISCOVERY'];h.context.pool=[{...flow(),id:'weak',mastery:0},s];let q=h.run('buildPracticeQueue(pool)');assert.equal(q[0].target,true);assert.equal(q[0].text,'Tell me about [their outcome].');h.context.pool[1].practiceTargets=['Renamed section'];q=h.run('buildPracticeQueue(pool)');assert.equal(q[0].target,false);assert.equal(q[0].text,s.text);});
test('timed practice ends after a completed rep at deadline and preserves full-script mastery for a section',()=>{const h=harness();const s=flow();s.practiceTargets=['2 - DISCOVERY'];h.context.scripts=[s];h.run('openDailySession(scripts,3)');assert.match(h.nodes['#sessionClock'].textContent,/3:00/);h.nodes.rate.choose(5);h.context.$('#sessionNote').value='Pause';h.advance(181000);assert.match(h.nodes['#sessionClock'].textContent,/Time is up/);h.nodes['#sessionNext'].onclick();assert.match(h.rendered,/1 reps completed/);assert.equal(s.mastery,2);const saved=JSON.parse(h.storage.get('scores'));assert.equal(saved[0].attempts[0].section,'2 - DISCOVERY');assert.equal(saved[0].attempts[0].note,'Pause');assert.ok(h.clearCount>0);});
test('ending a session without completing a rep does not create history',()=>{const h=harness();h.context.scripts=[flow()];h.run('openDailySession(scripts,5)');h.nodes['#endSession'].onclick();assert.equal(h.storage.has('scores'),false);assert.match(h.rendered,/0 reps completed/);});
test('backup request status distinguishes a download request from later changes',()=>{const h=harness();h.context.$=()=>null;h.run('recordExportRequest({sha256:"abc"})');let state=JSON.parse(h.storage.get('vault.export-status.v1'));assert.equal(state.dirty,false);h.run('markExportDirty()');state=JSON.parse(h.storage.get('vault.export-status.v1'));assert.equal(state.dirty,true);assert.equal(state.sha256,'abc');});
test('comparison notes are keyed to recording pair and media URLs are cleaned up',async()=>{let revoked=[],next=0;const h=harness({URL:{createObjectURL:()=>`blob:${++next}`,revokeObjectURL:u=>revoked.push(u)},getTakes:async()=>[{id:'new',date:2,blob:new Blob(['new'])},{id:'old',date:1,blob:new Blob(['old'])}],fmtDate:String});h.context.s=flow();h.nodes['#takeSelect0']={value:'old'};h.nodes['#takeSelect1']={value:'new'};await h.run('openComparison(s)');h.nodes['#comparisonNote'].value='More confident';h.nodes['#saveComparison'].onclick();assert.equal(h.context.s.comparisonNotes['old|new'],'More confident');h.nodes['#compareAudio0'].onplay();assert.equal(h.nodes['#compareAudio1'].paused,true);h.run('overlayCleanup()');assert.equal(revoked.length,2);});
